version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeperForMicro1
    networks:
      - kafka-micronaut-network
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181  # Specify the ZooKeeper client port

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafkaForMicro1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-micronaut-network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: KafkaUiForMicro1
    networks:
      - kafka-micronaut-network
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "7070:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: micronaut-kafka-cluster
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
networks:
  kafka-micronaut-network:
    driver: bridge