#Tue Aug 29 09:04:40 GMT 2023
micronaut:
  application:
    - name=kafkaDemoMicronaut

kafka:
  bootstrap:
    servers:
      - localhost:29092
#  producers:
#    product-client:
#      retries: 2
#      bootstrap:
#        servers: localhost:9092
#  producers:
#    default:
#      bootstrap:
#        servers: localhost:9092
